name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Updated to v4

      - name: Build with Buildozer
        # Using the official Buildozer Action maintainer
        uses: Niklas-Heer/buildozer-action@v1
        with:
          workdir: .
          buildozer_version: stable

      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # Updated to v4 to fix the error
        with:
          name: SteamApp-Package
          path: bin/*.apk
